### ISSUE TITLE
having a weird issue running this action

### ISSUE THREAD

**Issue by stakach** [crystal-ameba/github-action#15]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/368013/197466840-b1c25ac7-d843-492c-b346-4540209544d0.png">

Notice that it's using crystal 1.4.1 still?
However I can see that it's 1.6.0 in your latest release

hence it's failing with
![image](https://user-images.githubusercontent.com/368013/197467156-68654fcf-8dc7-4fb8-a7b5-5f12c6a5b2c8.png)

**Comment by veelenga** [comment]
Sorry, I forgot to release the version where the Crystal is bumped to 1.6. Please try `crystal-ameba/github-action@v0.5.1`
