### ISSUE TITLE
Failure in updating the PR with output from the linter.

### ISSUE THREAD

**Issue by antondalgren** [crystal-ameba/github-action#8]
The linting error ameba reported locally: `[C] Layout/TrailingWhitespace: Trailing whitespace detected`

> Unhandled exception: Response: Unprocessable Entity. Body: {"message":"Invalid request.\n\nFor 'properties/raw_details', nil is not a string.","documentation_url":"https://developer.github.com/v3/checks/runs/#update-a-check-run"} (Exception)
  from ../../app/src/ameba-github_action/github_client.cr:22:7 in 'handle_response'
  from ../../app/src/ameba-github_action/github_client.cr:18:7 in 'patch'
  from ../../app/src/ameba-github_action/runner.cr:62:7 in 'update_check'
  from ../../app/src/ameba-github_action/runner.cr:20:9 in 'run'
  from ../../app/src/ameba-github_action.cr:4:1 in '__crystal_main'
  from ../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
  from ../../usr/share/crystal/src/crystal/main.cr:91:7 in 'main'
  from ../../usr/share/crystal/src/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???

**Comment by veelenga** [comment]
Looks like github does not accept `nil` for `raw_details` property.

Thanks for reporting, going to handle this.
